import { Router } from "express";
import type { Request, Response } from "express";

const router = Router();

const PARAMETERS = [
  {
    id: "nvidia-drm-modeset",
    name: "nvidia-drm.modeset=1",
    category: "Graphics Subsystem",
    relevanceHybrid: 95,
    relevanceDgpu: 100,
    switches: "=1 (Enabled), =0 (Disabled)",
    recommendedValue: "nvidia-drm.modeset=1",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["nvidia", "drm", "wayland", "kde", "modeset"],
    verboseDescription: "Absolutely mandatory for modern NVIDIA Wayland compositing under KDE Plasma on Fedora 43 Rawhide. Setting this to 1 instructs the kernel to allow the NVIDIA proprietary driver to hook directly into the Direct Rendering Manager (DRM) subsystem. In a dGPU-only state, this ensures screen tearing is eliminated and display synchronization is handled natively by the NVIDIA hardware. In Hybrid mode, it acts as the necessary bridge for PRIME output synchronization — without it, KDE Plasma may fail to launch entirely on Wayland with the proprietary driver. Critical for the RTX 4060 Mobile GPU in the ASUS FX607V.",
  },
  {
    id: "intel-iommu",
    name: "intel_iommu=on iommu=pt",
    category: "Memory & Hardware Isolation",
    relevanceHybrid: 90,
    relevanceDgpu: 85,
    switches: "intel_iommu=on/off/igfx_off, iommu=pt/force",
    recommendedValue: "intel_iommu=on iommu=pt",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["iommu", "memory", "dma", "virtualization", "ddr5"],
    verboseDescription: "Crucial for optimizing your 16 GB DDR5 dual-channel memory on the ASUS FX607V architecture. 'intel_iommu=on' activates the Input-Output Memory Management Unit, a hardware feature vital for secure memory isolation and virtualization. 'iommu=pt' (passthrough) is the optimization catalyst: it prevents the kernel from unnecessarily translating DMA requests for trusted devices, reducing overhead and improving NVMe SSD throughput. Replacing the bare 'iommu' flag with this explicit pair ensures correct behavior across kernel versions 6.8+ used in Fedora 43 Rawhide.",
  },
  {
    id: "acpi-osi",
    name: "acpi_osi=Linux",
    category: "ASUS Firmware & ACPI",
    relevanceHybrid: 85,
    relevanceDgpu: 85,
    switches: "acpi_osi=Linux, acpi_osi=\"!Windows 2020\", acpi_osi=off",
    recommendedValue: "acpi_osi=Linux",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["acpi", "asus", "bios", "v340", "firmware", "hotkeys"],
    verboseDescription: "An aggressive workaround for the ASUS BIOS v340. Laptop manufacturers often hardcode ACPI tables to expect a Windows environment. By forcing 'acpi_osi=Linux', you command the kernel to present itself strictly as a Linux environment to the firmware. This can resolve issues with Fn key brightness controls, fan speed profiles, and ASUS-specific ACPI methods on the FX607V. Alternatively, '!Windows 2020' spoofs a specific Windows version to unlock Embedded Controller features. Test both on Fedora 43 Rawhide if hotkeys malfunction.",
  },
  {
    id: "nouveau-blacklist",
    name: "rd.driver.blacklist=nouveau modprobe.blacklist=nouveau",
    category: "Graphics Subsystem",
    relevanceHybrid: 80,
    relevanceDgpu: 100,
    switches: "blacklist=module_name (comma-separated list supported)",
    recommendedValue: "rd.driver.blacklist=nouveau modprobe.blacklist=nouveau",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["nouveau", "nvidia", "blacklist", "dracut", "kernel-module"],
    verboseDescription: "The absolute eradication of the open-source nouveau driver from the boot sequence. When forcing dGPU-only mode, any accidental loading of nouveau by the initial ramdisk (dracut) will cause a catastrophic race condition with the proprietary NVIDIA drivers, resulting in kernel panics or a black screen on Fedora 43 Rawhide. 'rd.driver.blacklist' prevents loading during dracut/initrd phase; 'modprobe.blacklist' prevents loading post-init. Both are required for complete blacklisting. Safe to apply in Hybrid mode as well — the NVIDIA proprietary stack provides full replacement.",
  },
  {
    id: "rhgb-quiet-remove",
    name: "rhgb quiet (REMOVE for debugging)",
    category: "Diagnostics & Verbosity",
    relevanceHybrid: 70,
    relevanceDgpu: 75,
    switches: "N/A — remove these flags entirely for verbose output",
    recommendedValue: "Remove both flags during debugging",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["rhgb", "quiet", "debug", "verbose", "plymouth"],
    verboseDescription: "While standard on Fedora, removing 'rhgb' (Red Hat Graphical Boot) and 'quiet' is strongly advised for Fedora 43 Rawhide development releases. These flags mask critical kernel initialization logs. Removing them exposes raw standard output as the kernel probes your Intel/NVIDIA hybrid architecture and initializes your 16GB DDR5. If the ASUS v340 BIOS causes a hang during PCIe enumeration of the RTX 4060 Mobile, seeing the raw diagnostic stream is the only way to identify the hanging subsystem. Re-add after debugging is complete for normal use.",
  },
  {
    id: "pcie-aspm",
    name: "pcie_aspm=off",
    category: "Power & PCIe Bus",
    relevanceHybrid: 30,
    relevanceDgpu: 95,
    switches: "=off, =force, =default",
    recommendedValue: "pcie_aspm=off (dGPU only), omit in Hybrid",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["pcie", "aspm", "power", "dgpu", "performance"],
    verboseDescription: "Active State Power Management controls power consumption on PCI Express links. In Hybrid mode, ASPM is vital to allow the NVIDIA GPU to reach RTD3 (Runtime D3) sleep state, saving battery. In strict dGPU mode for maximum performance, 'pcie_aspm=off' disables these power-saving states, forcing the PCIe lanes to remain fully saturated. This can resolve timing instabilities with the RTX 4060 Mobile on BIOS v340 when ASPM negotiation fails silently. Use only when maximizing GPU performance and plugged into AC power.",
  },
  {
    id: "i915-guc",
    name: "i915.enable_guc=3",
    category: "Graphics Subsystem",
    relevanceHybrid: 100,
    relevanceDgpu: 10,
    switches: "=0 (Off), =1 (Default), =2 (HuC only), =3 (GuC+HuC)",
    recommendedValue: "i915.enable_guc=3",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["i915", "intel", "guc", "huc", "hybrid", "igpu"],
    verboseDescription: "A highly specialized Intel Graphics (i915) parameter critical for Hybrid mode. Setting to 3 enables both the GuC (Graphics microController) for advanced workload scheduling and the HuC (HEVC microController) for hardware-accelerated video decoding. This significantly offloads processing from the CPU to the Intel Iris Xe iGPU, preserving your 16GB DDR5 bandwidth for the RTX 4060 Mobile when PRIME offloading is triggered. On Fedora 43 Rawhide with kernel 6.8+, GuC submission is the preferred rendering path for Intel GPUs. Irrelevant in pure dGPU mode where the iGPU is disabled.",
  },
  {
    id: "zswap",
    name: "zswap.enabled=1 zswap.max_pool_percent=15",
    category: "Memory & Hardware Isolation",
    relevanceHybrid: 75,
    relevanceDgpu: 75,
    switches: "enabled=0/1, max_pool_percent=[0-100], compressor=lz4/zstd/deflate",
    recommendedValue: "zswap.enabled=1 zswap.max_pool_percent=15 zswap.compressor=zstd",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["memory", "swap", "zswap", "ddr5", "compression", "performance"],
    verboseDescription: "With your FX607V upgraded to 16 GB DDR5, swap thrashing to the NVMe SSD can still occur during extreme compilation or massive KDE Plasma memory leaks on Fedora 43 Rawhide. Zswap acts as a compressed RAM cache for swap pages. Setting max_pool_percent=15 restricts it to ~2.4 GB of your 16GB total, intercepting memory pages headed for the SSD, compressing them with zstd, and storing them in RAM. Throughput drops from NVMe speeds to RAM speeds — a major performance win. Recommended alongside zram for Rawhide development workloads.",
  },
  {
    id: "nvidia-modeset",
    name: "nvidia.NVreg_PreserveVideoMemoryAllocations=1",
    category: "Graphics Subsystem",
    relevanceHybrid: 88,
    relevanceDgpu: 92,
    switches: "=1 (Enabled), =0 (Disabled)",
    recommendedValue: "nvidia.NVreg_PreserveVideoMemoryAllocations=1",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["nvidia", "vram", "suspend", "hibernate", "memory"],
    verboseDescription: "Critical for suspend/resume stability with the NVIDIA RTX 4060 Mobile. Without this parameter, the NVIDIA driver frees VRAM allocations on system suspend, causing the GPU to lose its framebuffer state. On resume, KDE Plasma may fail to restore the display. Setting this to 1 instructs the driver to preserve video memory during sleep states. Essential on the FX607V since ASUS implements D3cold power states for the dGPU during battery save. Works in conjunction with the NVIDIA system services 'nvidia-suspend.service' and 'nvidia-resume.service' on Fedora.",
  },
  {
    id: "acpi-backlight",
    name: "acpi_backlight=vendor",
    category: "ASUS Firmware & ACPI",
    relevanceHybrid: 78,
    relevanceDgpu: 60,
    switches: "=vendor, =video, =native, =none",
    recommendedValue: "acpi_backlight=vendor",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["acpi", "backlight", "brightness", "asus", "display"],
    verboseDescription: "Controls which kernel subsystem manages display brightness. On the ASUS FX607V with BIOS v340, the default 'video' driver may conflict with the ASUS-specific ACPI backlight interface, resulting in brightness keys that work but don't actually change screen brightness, or a screen stuck at maximum brightness. 'vendor' forces the use of the ASUS-specific ACPI backlight interface. 'native' uses the display driver directly. Test 'vendor' first on Fedora 43 Rawhide — it resolves issues on most recent ASUS TUF models.",
  },
  {
    id: "amd-pstate",
    name: "amd_pstate=active",
    category: "CPU & Power Management",
    relevanceHybrid: 82,
    relevanceDgpu: 70,
    switches: "=active (CPPC preferred), =passive (scaled), =guided",
    recommendedValue: "amd_pstate=active",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["cpu", "pstate", "power", "performance", "amd", "ryzen"],
    verboseDescription: "NOTE: Only relevant if your FX607V has an AMD CPU variant. For the Intel Core i7-13650HX variant, use intel_pstate instead. 'amd_pstate=active' enables Collaborative Processor Performance Control (CPPC), allowing the CPU and OS to cooperatively manage frequency scaling. This provides finer-grained frequency steps than the legacy ACPI cpufreq driver, reducing power consumption during idle states while maintaining burst performance. On Fedora 43 Rawhide, 'active' mode is preferred over 'guided' for KDE Plasma workloads with frequent burst activity.",
  },
  {
    id: "intel-pstate",
    name: "intel_pstate=active",
    category: "CPU & Power Management",
    relevanceHybrid: 85,
    relevanceDgpu: 72,
    switches: "=active, =passive, =no_hwp, =force, =off",
    recommendedValue: "intel_pstate=active",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["cpu", "intel", "pstate", "hwp", "power", "performance"],
    verboseDescription: "For the Intel Core i7-13650HX in the ASUS FX607V. The 'intel_pstate' driver manages CPU frequency scaling using Intel's Hardware-Controlled Performance (HWP). 'active' mode (default) uses HWP with the kernel EPP (Energy Performance Preference) hint. 'passive' hands control to the generic CPUfreq governors (schedutil, powersave). If you experience thermal throttling or unpredictable boost behavior on Fedora 43 Rawhide, try 'passive' with the 'schedutil' governor, which is better integrated with the Linux scheduler's load metrics on modern Intel 13th-gen hybrid architectures.",
  },
  {
    id: "mem-sleep-default",
    name: "mem_sleep_default=deep",
    category: "CPU & Power Management",
    relevanceHybrid: 72,
    relevanceDgpu: 50,
    switches: "=deep (S3 suspend-to-RAM), =s2idle (S0ix connected standby)",
    recommendedValue: "mem_sleep_default=deep",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["sleep", "suspend", "power", "s3", "acpi", "battery"],
    verboseDescription: "On many modern ASUS laptops including the FX607V, the ASUS BIOS v340 may default to 's2idle' (Modern Standby / S0ix), which keeps the system in a low-power connected state rather than fully suspending. This can cause excessive battery drain during sleep on Linux. Forcing 'mem_sleep_default=deep' selects S3 (traditional suspend-to-RAM), which properly powers down most subsystems including the PCIe bus and GPU. This dramatically reduces sleep power consumption. Verify BIOS settings also have 'Sleep Type' set to 'S3' — some ASUS BIOS versions only expose S0ix.",
  },
  {
    id: "kernel-lockdown",
    name: "lockdown=integrity",
    category: "Security & Integrity",
    relevanceHybrid: 40,
    relevanceDgpu: 40,
    switches: "=integrity, =confidentiality, =none",
    recommendedValue: "Omit on development systems, use on production",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["security", "lockdown", "secureboot", "kernel", "modules"],
    verboseDescription: "Kernel Lockdown restricts actions that could compromise kernel integrity. 'integrity' mode prevents unsigned kernel modules from loading and blocks /dev/mem access. CRITICAL: On Fedora 43 Rawhide, this WILL block proprietary NVIDIA drivers unless they are signed with your Secure Boot key via 'mokutil'. On a development release, this parameter is generally counterproductive — it prevents loading out-of-tree modules needed for testing. Only add this parameter if you have enrolled your MOK (Machine Owner Key) with 'mokutil --import' and have signed the NVIDIA .ko files.",
  },
  {
    id: "mitigations-off",
    name: "mitigations=off",
    category: "Security & Integrity",
    relevanceHybrid: 35,
    relevanceDgpu: 45,
    switches: "=off (all disabled), =auto (default), =auto,nosmt",
    recommendedValue: "mitigations=auto (default, omit this flag)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["security", "spectre", "meltdown", "performance", "cpu"],
    verboseDescription: "Disables all CPU vulnerability mitigations (Spectre, Meltdown, MDS, TAA, etc.). On the Intel Core i7-13650HX, mitigations have a measurable performance impact — approximately 5-15% on workloads with heavy syscall rates. 'mitigations=off' recovers this performance at the cost of exposing the system to CPU side-channel attacks. SECURITY WARNING: Appropriate ONLY for isolated development VMs or bare-metal systems with complete physical security. Never use on systems with untrusted users or public network exposure. The FX607V running Fedora 43 Rawhide as a development machine may benefit marginally from this in air-gapped environments.",
  },
  {
    id: "transparent-hugepages",
    name: "transparent_hugepage=madvise",
    category: "Memory & Hardware Isolation",
    relevanceHybrid: 65,
    relevanceDgpu: 65,
    switches: "=always, =madvise, =never",
    recommendedValue: "transparent_hugepage=madvise",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["memory", "hugepages", "thp", "performance", "ddr5"],
    verboseDescription: "Controls Transparent Huge Page (THP) allocation behavior. 'always' eagerly allocates 2MB pages, reducing TLB pressure but increasing latency during allocation. 'madvise' only uses huge pages for memory regions that explicitly request them via the madvise() syscall, providing better control. 'never' disables THP entirely, which some Redis and Java workloads actually prefer. For Fedora 43 Rawhide with 16GB DDR5 on the FX607V, 'madvise' is the most balanced choice — KDE Plasma and typical development workloads benefit from selective huge page use without the fragmentation overhead of 'always'.",
  },
  {
    id: "rd-luks",
    name: "rd.luks.options=discard",
    category: "Storage & Filesystem",
    relevanceHybrid: 70,
    relevanceDgpu: 70,
    switches: "discard, no-read-workqueue, no-write-workqueue, same-cpu-crypt",
    recommendedValue: "rd.luks.options=discard,no-read-workqueue,no-write-workqueue",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["luks", "encryption", "nvme", "storage", "discard", "trim"],
    verboseDescription: "Optimizes LUKS full-disk encryption for NVMe SSDs. 'discard' enables TRIM/discard passthrough to the SSD, essential for maintaining performance and longevity on NVMe drives — without it, the encrypted volume can't inform the SSD which blocks are free. 'no-read-workqueue' and 'no-write-workqueue' bypass dm-crypt's async work queues for synchronous I/O, reducing latency for random reads/writes. Significant on Fedora 43 Rawhide where dracut initializes the LUKS volume early. Security note: 'discard' slightly leaks information about encrypted data layout to physical attackers — acceptable for most laptop threat models.",
  },
  {
    id: "rootflags-subvol",
    name: "rootflags=subvol=root",
    category: "Storage & Filesystem",
    relevanceHybrid: 95,
    relevanceDgpu: 95,
    switches: "subvol=<name>, subvolid=<id>, compress=zstd:3, autodefrag",
    recommendedValue: "rootflags=subvol=root,compress=zstd:3",
    positionalParams: "subvol name (positional in BTRFS mount args)",
    riskLevel: "safe",
    tags: ["btrfs", "subvolume", "filesystem", "fedora", "root"],
    verboseDescription: "Specifies BTRFS subvolume mount options passed to the kernel at boot. 'subvol=root' mounts the 'root' subvolume as the root filesystem — standard Fedora BTRFS layout. Adding 'compress=zstd:3' enables real-time BTRFS transparent compression with zstd at compression level 3. On the FX607V's NVMe SSD, this trades negligible CPU overhead (your i7-13650HX handles zstd extremely efficiently) for 20-40% storage savings on typical filesystems, reduced write amplification, and extended SSD lifespan. Particularly effective on Fedora 43 Rawhide's development package cache which contains many compressible RPM files.",
  },
  {
    id: "systemd-debug",
    name: "systemd.log_level=debug",
    category: "Diagnostics & Verbosity",
    relevanceHybrid: 45,
    relevanceDgpu: 45,
    switches: "=debug, =info, =warning, =err, =crit",
    recommendedValue: "systemd.log_level=debug (use only for debugging boots)",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["systemd", "debug", "logging", "diagnostics", "boot"],
    verboseDescription: "Forces systemd to emit debug-level logs during boot, captured by journald. On Fedora 43 Rawhide — a development release where services may fail silently — this is invaluable for tracing service dependency failures, socket activation issues, or udev rule conflicts during early boot. The ASUS FX607V v340 BIOS can trigger unusual ACPI device enumeration that confuses systemd-udevd; debug logging captures the exact device probe sequence. After capturing the journal with 'journalctl -b', restore normal logging by removing this parameter to avoid journal storage bloat.",
  },
  {
    id: "numa-off",
    name: "numa=off",
    category: "Memory & Hardware Isolation",
    relevanceHybrid: 25,
    relevanceDgpu: 25,
    switches: "=off",
    recommendedValue: "Omit — not applicable to single-socket laptops",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["numa", "memory", "topology", "performance"],
    verboseDescription: "Disables NUMA (Non-Uniform Memory Access) topology awareness in the kernel. The FX607V is a single-socket laptop with a single memory controller, so true NUMA does not apply. However, some BIOSes (including certain ASUS versions) incorrectly expose fake NUMA nodes via ACPI SRAT tables, confusing the kernel memory allocator and causing suboptimal page allocation. If your BIOS v340 reports multiple NUMA nodes in /proc/buddyinfo, enabling 'numa=off' flattens the topology and restores optimal memory allocation. Check with 'numactl --hardware' before applying.",
  },
  {
    id: "nvidia-open",
    name: "nvidia_drm.fbdev=1",
    category: "Graphics Subsystem",
    relevanceHybrid: 72,
    relevanceDgpu: 88,
    switches: "=1 (Enable framebuffer device), =0 (Disabled)",
    recommendedValue: "nvidia_drm.fbdev=1",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["nvidia", "framebuffer", "drm", "console", "tty"],
    verboseDescription: "Enables the NVIDIA DRM framebuffer device, allowing the Linux kernel's VT (virtual terminal) console to use the NVIDIA GPU directly instead of falling back to efifb or vesafb. On Fedora 43 Rawhide, this resolves the 'black screen' issue between GRUB and the KDE SDDM login manager where the framebuffer handoff fails silently. Required when using the open-source NVIDIA kernel module (nvidia-open) on RTX 40-series GPUs. The RTX 4060 Mobile in the FX607V supports GSP (GPU System Processor) firmware which is required for nvidia-open module compatibility on Fedora.",
  },
  {
    id: "rd-timeout",
    name: "rd.timeout=90",
    category: "Storage & Filesystem",
    relevanceHybrid: 55,
    relevanceDgpu: 55,
    switches: "=<seconds> (integer, default is kernel/dracut default)",
    recommendedValue: "rd.timeout=90",
    positionalParams: "timeout value in seconds",
    riskLevel: "safe",
    tags: ["dracut", "boot", "timeout", "storage", "luks"],
    verboseDescription: "Sets the maximum time dracut (the initramfs generator) will wait for devices to appear before giving up and dropping to an emergency shell. On Fedora 43 Rawhide, the NVMe device on the FX607V normally appears within 2-3 seconds, but encrypted LUKS volumes or BTRFS arrays can occasionally take longer, especially after an unclean shutdown. If you see 'Warning: /dev/disk/by-uuid/... does not exist' during boot followed by a 90-second countdown, this parameter extends that window. Increase to 90 if LUKS prompt timing is unreliable.",
  },
  {
    id: "audit-off",
    name: "audit=0",
    category: "Security & Integrity",
    relevanceHybrid: 50,
    relevanceDgpu: 50,
    switches: "=0 (Disabled), =1 (Enabled, default)",
    recommendedValue: "audit=0 (development systems only)",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["audit", "security", "performance", "syscall", "selinux"],
    verboseDescription: "Disables the Linux Audit subsystem at boot. On Fedora 43 Rawhide with SELinux enabled, the audit subsystem logs every SELinux AVC denial, policy lookup, and security event. While essential for production security hardening, on a development system with frequent AVC denials from new/unsigned software, audit logging adds measurable overhead to syscall paths and fills journald rapidly. Disabling with 'audit=0' removes this overhead. WARNING: This also disables auditd-based intrusion detection. Appropriate for isolated development workstations — restore 'audit=1' on any system handling sensitive data.",
  },
  {
    id: "usbcore-autosuspend",
    name: "usbcore.autosuspend=-1",
    category: "CPU & Power Management",
    relevanceHybrid: 60,
    relevanceDgpu: 55,
    switches: "=-1 (Disabled), =0 (Immediate), =<seconds>",
    recommendedValue: "usbcore.autosuspend=-1 (if USB devices behave erratically)",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["usb", "power", "autosuspend", "peripheral"],
    verboseDescription: "Controls the USB autosuspend timeout, which automatically powers down idle USB devices to save energy. The default allows the kernel to suspend unused USB devices after 2 seconds. On the ASUS FX607V, certain USB peripherals (particularly USB-C docks, gaming mice with firmware, and the internal USB hub connecting the keyboard controller) can behave erratically or lose connectivity when autosuspended. Setting to -1 disables autosuspend globally. For targeted control, use udev rules to disable autosuspend per-device without affecting others — see /sys/bus/usb/devices/*/power/autosuspend.",
  },
  {
    id: "video-port",
    name: "video=eDP-1:1920x1080@144",
    category: "Display & Output",
    relevanceHybrid: 65,
    relevanceDgpu: 80,
    switches: "video=<connector>:<resolution>@<refresh>, video=HDMI-A-1:1920x1080@60",
    recommendedValue: "video=eDP-1:1920x1080@144",
    positionalParams: "connector name, resolution string (WxH), refresh rate (Hz)",
    riskLevel: "safe",
    tags: ["display", "resolution", "edp", "refresh", "144hz", "framebuffer"],
    verboseDescription: "Forces the kernel framebuffer to a specific resolution and refresh rate on a named connector. The ASUS FX607V features a 144Hz FHD (1920x1080) IPS display on the internal eDP connector. During early boot before the NVIDIA or Intel driver takes control, the kernel framebuffer defaults to a lower resolution. Specifying 'video=eDP-1:1920x1080@144' maintains native resolution throughout the boot sequence, preventing resolution flicker at SDDM login. In dGPU mode with PRIME output, the display may be named differently — check 'xrandr' or 'kscreen-doctor --outputs' to identify the correct connector name.",
  },
  {
    id: "rd-blacklist-nouveau",
    name: "rd.blacklist=nouveau",
    category: "Graphics Subsystem",
    relevanceHybrid: 75,
    relevanceDgpu: 98,
    switches: "=<module_name> (dracut-specific early blacklist)",
    recommendedValue: "rd.blacklist=nouveau",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["dracut", "nouveau", "blacklist", "initrd", "early-boot"],
    verboseDescription: "Dracut-specific parameter to blacklist the nouveau module during the initramfs phase — before the regular modprobe.blacklist takes effect. This is the earliest possible stage to prevent nouveau from loading. Critical distinction from 'rd.driver.blacklist': this parameter is processed by the dracut-specific cmdline hook, while 'rd.driver.blacklist' is processed by the dracut network/driver detection hook. Use both for complete coverage. The ASUS FX607V's RTX 4060 Mobile has excellent nouveau support in theory, but its presence conflicts catastrophically with the proprietary NVIDIA 550+ drivers on Fedora 43 Rawhide.",
  },
  {
    id: "btrfs-compression",
    name: "rootflags=compress=zstd:3",
    category: "Storage & Filesystem",
    relevanceHybrid: 68,
    relevanceDgpu: 68,
    switches: "compress=zstd:1-22, compress=lzo, compress=zlib:1-9, compress-force=<algo>",
    recommendedValue: "rootflags=subvol=root,compress=zstd:3",
    positionalParams: "compression algorithm name, compression level",
    riskLevel: "safe",
    tags: ["btrfs", "compression", "zstd", "storage", "performance"],
    verboseDescription: "Enables BTRFS transparent filesystem compression at the kernel level. Level 3 provides the best balance between compression ratio and CPU overhead for the Intel Core i7-13650HX — lower levels (1-2) compress faster with less ratio; higher levels (4+) compress better but add perceptible latency to write paths. 'compress-force' applies compression even to data that may not compress well (useful for forcing uniform behavior). On Fedora 43 Rawhide, the development package cache, source trees, and compiled intermediate objects compress 30-50%, significantly reducing NVMe write amplification and extending drive longevity over years of development use.",
  },
  {
    id: "nmi-watchdog",
    name: "nmi_watchdog=0",
    category: "CPU & Power Management",
    relevanceHybrid: 40,
    relevanceDgpu: 40,
    switches: "=0 (Disabled), =1 (Enabled via perf events), =2 (Enabled via I/O APIC)",
    recommendedValue: "nmi_watchdog=0 (saves power, minor perf benefit)",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["watchdog", "nmi", "power", "performance", "cpu"],
    verboseDescription: "The NMI (Non-Maskable Interrupt) watchdog uses hardware performance counters to detect kernel hangs. Disabling it frees one PMU (Performance Monitoring Unit) counter for use by perf, eBPF tools, and profiling applications — valuable on Fedora 43 Rawhide development systems where perf/BPF tooling is frequently used. Also reduces power consumption marginally since the watchdog generates periodic NMI interrupts. On stable production systems, keep this enabled. On a Fedora Rawhide development machine where kernel panics are occasionally expected (it's a pre-release!), the watchdog overhead outweighs its benefit.",
  },
  {
    id: "selinux-permissive",
    name: "enforcing=0",
    category: "Security & Integrity",
    relevanceHybrid: 55,
    relevanceDgpu: 55,
    switches: "=0 (Permissive/log-only), =1 (Enforcing, default)",
    recommendedValue: "enforcing=0 (Rawhide development only, remove for production)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["selinux", "security", "permissive", "avc", "fedora"],
    verboseDescription: "Places SELinux in Permissive mode — policy violations are logged but not blocked. On Fedora 43 Rawhide, new kernel features, unsigned drivers, and experimental software frequently generate SELinux AVC denials that block execution in Enforcing mode. Setting 'enforcing=0' at boot allows the system to function while you audit denials with 'ausearch -m avc' and generate policy fixes with 'audit2allow'. SECURITY WARNING: Permissive mode provides NO MAC (Mandatory Access Control) protection. Legitimate for isolated development workstations testing unstable Fedora packages. Absolutely prohibited on any multi-user or network-facing system.",
  },
  {
    id: "tsc-reliable",
    name: "tsc=reliable",
    category: "CPU & Power Management",
    relevanceHybrid: 48,
    relevanceDgpu: 48,
    switches: "=reliable, =unstable, =nowatchdog",
    recommendedValue: "Omit unless experiencing clock instability",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["tsc", "clocksource", "timing", "cpu", "intel"],
    verboseDescription: "Instructs the kernel to trust the Time Stamp Counter (TSC) as a reliable clocksource. On the Intel Core i7-13650HX, the TSC is hardware-synchronized across efficiency and performance cores using Intel's TSC invariant feature. Normally, the kernel self-detects TSC reliability. If you see kernel messages about 'TSC being unstable' or 'clocksource: Switched to clocksource tsc-early' followed by time drift in KDE Plasma system clock, explicitly marking TSC as reliable stops the fallback to HPET (which is slower). On ASUS BIOS v340, this is rarely needed but may help if BIOS configures C-state transitions aggressively.",
  },
  {
    id: "asus-wmi",
    name: "asus_wmi.fnlock_default=1",
    category: "ASUS Firmware & ACPI",
    relevanceHybrid: 60,
    relevanceDgpu: 60,
    switches: "=0 (Fn keys as F1-F12), =1 (Fn keys as media/control)",
    recommendedValue: "asus_wmi.fnlock_default=1",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["asus", "wmi", "fnlock", "keyboard", "hotkeys"],
    verboseDescription: "A highly specific quality-of-life module parameter for the 'asus_wmi' kernel driver. ASUS TUF laptops often have ambiguous default states for their Function (Fn) key rows. This parameter instructs the Windows Management Instrumentation (WMI) ACPI bridge to default the Fn keys to their media/control functions rather than standard F1-F12 keys upon boot. This bypasses the need to rely on userspace tools (like asusctl) to set the hardware flag after the graphical session has already initialized.",
  },
  {
    id: "nvidia-drm-fbdev",
    name: "nvidia-drm.fbdev=1",
    category: "Graphics Subsystem",
    relevanceHybrid: 85,
    relevanceDgpu: 100,
    switches: "=1 (Enabled), =0 (Disabled)",
    recommendedValue: "nvidia-drm.fbdev=1",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["nvidia", "drm", "fbdev", "framebuffer", "tty", "wayland"],
    verboseDescription: "An absolutely vital parameter for modern NVIDIA proprietary drivers (version 550+) operating within the volatile environment of Fedora 43 KDE Wayland. This parameter forcefully creates a high-resolution frame buffer device backed by the NVIDIA GPU. When operating in dGPU override mode, this ensures the TTY virtual consoles (Ctrl+Alt+F3) render at your ASUS F16's native resolution rather than defaulting to a catastrophic blank screen or corrupted VGA text mode, enabling critical emergency terminal access.",
  },
  {
    id: "ibt-off",
    name: "ibt=off",
    category: "Processor & Security",
    relevanceHybrid: 80,
    relevanceDgpu: 95,
    switches: "ibt=off, ibt=on (default)",
    recommendedValue: "ibt=off (only when NVIDIA driver rejects due to IBT conflict)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["ibt", "intel", "security", "nvidia", "module", "kernel"],
    verboseDescription: "Indirect Branch Tracking (IBT) is a hardware-level security mitigation native to newer Intel processors present in the ASUS FX607V. However, the proprietary NVIDIA driver modules injected into the Rawhide kernel frequently fail to bind with IBT enforced, resulting in a fatal 'module verification failed' panic during dracut initialization. Disabling IBT neutralizes this conflict, trading a highly specific vector of buffer overflow protection for absolute graphical driver stability in a development environment. Re-enable once NVIDIA drivers fully support IBT.",
  },
  {
    id: "i915-psr",
    name: "i915.enable_psr=0",
    category: "Graphics Subsystem",
    relevanceHybrid: 100,
    relevanceDgpu: 5,
    switches: "=0 (Disabled), =1 (Enabled), =2 (Selective Update)",
    recommendedValue: "i915.enable_psr=0",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["i915", "intel", "psr", "display", "flicker", "hybrid", "wayland"],
    verboseDescription: "Panel Self Refresh (PSR) is a power-saving state for the Intel iGPU that instructs the display panel to hold a static frame without the GPU constantly feeding it. On the ASUS TUF series running KDE Plasma under Wayland, the synchronization between PSR and the rapid compositor updates often results in aggressive micro-flickering or partial screen tearing. Disabling this via '=0' forces constant display updates, sacrificing a marginal amount of battery life for absolute visual fidelity in Hybrid mode. Only relevant when Intel iGPU is driving the display.",
  },
  {
    id: "nvme-power-latency",
    name: "nvme_core.default_ps_max_latency_us=0",
    category: "Storage Subsystem",
    relevanceHybrid: 40,
    relevanceDgpu: 90,
    switches: "=0 (Disable all NVMe power states), =[integer] (microseconds)",
    recommendedValue: "nvme_core.default_ps_max_latency_us=0 (if NVMe causes IO freezes)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["nvme", "storage", "power", "apst", "latency", "freeze"],
    verboseDescription: "ASUS TUF laptops typically utilize high-speed PCIe Gen4 NVMe drives that feature aggressive Autonomous Power State Transitions (APST). On Fedora Rawhide, entering these deep sleep states can cause a microsecond lockup that completely freezes the root filesystem. Setting the max latency to 0 disables APST entirely. While it slightly increases the thermal output of the SSD, it guarantees zero-latency access to the storage drive during intensive dGPU workloads. Start with a higher value (e.g., 5500) before going to 0.",
  },
  {
    id: "split-lock-detect",
    name: "split_lock_detect=off",
    category: "Processor & Scheduling",
    relevanceHybrid: 60,
    relevanceDgpu: 85,
    switches: "=off, =warn (default), =fatal",
    recommendedValue: "split_lock_detect=off (gaming/Proton environments)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["intel", "cpu", "split-lock", "proton", "wine", "gaming", "latency"],
    verboseDescription: "Modern Intel processors hardware-trap 'split locks' — atomic operations that cross cache line boundaries — and the Linux kernel heavily penalizes tasks that trigger them to prevent bus lockups. Unfortunately, many older Windows games run via Proton/Wine and specific development emulators trigger split locks constantly. Disabling the detection entirely prevents the kernel from throttling these processes, ensuring smooth performance at the cost of potential localized bus contention.",
  },
  {
    id: "sig-enforce",
    name: "module.sig_enforce=0",
    category: "System Core & Security",
    relevanceHybrid: 60,
    relevanceDgpu: 60,
    switches: "=0 (Disabled), =1 (Enforce, default)",
    recommendedValue: "module.sig_enforce=0 (development only, never production)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["module", "signing", "security", "nvidia", "kernel", "rawhide"],
    verboseDescription: "Fedora Rawhide utilizes strict kernel module signing. When compiling experimental out-of-tree drivers — such as modified 'asus_wmi' modules or custom NVIDIA driver patches — the kernel will reject them if they lack cryptographic signatures. Setting this parameter to 0 bypasses the verification entirely. The kernel will taint itself (logging a warning) but will unconditionally load any compiled module, allowing unrestricted hardware development and testing. Never use on a multi-user or networked production system.",
  },
  {
    id: "i8042-nopnp",
    name: "i8042.nopnp i8042.reset",
    category: "ASUS Firmware & ACPI",
    relevanceHybrid: 65,
    relevanceDgpu: 65,
    switches: "nopnp (bypass PNP), reset (force controller reset), nomux, noloop",
    recommendedValue: "i8042.nopnp i8042.reset (if keyboard fails during early boot)",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["i8042", "keyboard", "ps2", "acpi", "asus", "bios", "boot"],
    verboseDescription: "A deeply embedded fix for the archaic PS/2 interface that modern laptops still use to route integrated keyboards and touchpads. The ASUS BIOS v340 sometimes misreports the status of these devices via Plug and Play (PNP). Passing 'nopnp' forces the kernel to bypass ACPI probing and query the controller directly, while 'reset' forces a hardware initialization of the controller. This acts as a fail-safe against the F16's integrated keyboard failing to respond during early boot sequences.",
  },
  {
    id: "max-cstate",
    name: "processor.max_cstate=4",
    category: "Power & PCIe Bus",
    relevanceHybrid: 40,
    relevanceDgpu: 85,
    switches: "=0 (C0 only), =1 (C1), =4 (C4), =5 (C5), =9 (All states)",
    recommendedValue: "processor.max_cstate=4 (balance) or =1 (max perf)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["cpu", "cstate", "power", "latency", "nvidia", "stability"],
    verboseDescription: "A specialized parameter that restricts the deepest power-saving states (C-states) the Intel processor can enter. When operating under extreme loads with the NVIDIA dGPU fully saturated, allowing the CPU to drop into C8 or C10 sleep states between instruction cycles can result in voltage droop, crashing the system under heavy transient loads. Restricting to C4 ensures the CPU remains partially energized, increasing stability during aggressive workload switching at the cost of higher idle thermal output.",
  },
  {
    id: "page-alloc-shuffle",
    name: "page_alloc.shuffle=1",
    category: "Memory & Hardware Isolation",
    relevanceHybrid: 80,
    relevanceDgpu: 80,
    switches: "=0 (Disabled, default), =1 (Enabled)",
    recommendedValue: "page_alloc.shuffle=1",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["memory", "ddr5", "security", "heap", "allocation", "kaslr"],
    verboseDescription: "An obscure optimization explicitly beneficial for your dual-channel 16GB DDR5 memory arrays. Standard Linux memory allocation is sequential, which can wear out specific memory banks faster and allows predictable memory patterns for side-channel attacks. Setting this to 1 introduces a randomized shuffling of the Free Page list. This acts as a wear-leveling mechanism for DDR5 modules, distributing electrical load evenly across all memory banks and simultaneously increasing system security.",
  },
  {
    id: "nvidia-preserve-vram",
    name: "nvidia.NVreg_PreserveVideoMemoryAllocations=1",
    category: "Graphics Subsystem",
    relevanceHybrid: 90,
    relevanceDgpu: 100,
    switches: "=1 (Enabled), =0 (Disabled, default)",
    recommendedValue: "nvidia.NVreg_PreserveVideoMemoryAllocations=1",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["nvidia", "vram", "suspend", "resume", "wayland", "kde", "s3"],
    verboseDescription: "A mandatory parameter for surviving Wayland sleep/wake cycles on Fedora 43 Rawhide. Without this, the proprietary NVIDIA driver will purge its VRAM buffer during an ACPI S3 sleep event, causing KDE Plasma to exhibit visual corruption upon wake. Injecting this parameter forces the kernel to serialize the entire VRAM payload into your 16GB DDR5 matrix or NVMe swap space, preserving the graphical topology flawlessly across suspend/resume cycles.",
  },
  {
    id: "nvidia-dynamic-pm",
    name: "nvidia.NVreg_DynamicPowerManagement=0x02",
    category: "Power & PCIe Bus",
    relevanceHybrid: 100,
    relevanceDgpu: 20,
    switches: "=0x00 (Off), =0x01 (Coarse), =0x02 (Fine-grained)",
    recommendedValue: "nvidia.NVreg_DynamicPowerManagement=0x02",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["nvidia", "power", "d3cold", "rtd3", "hybrid", "battery", "pcie"],
    verboseDescription: "Setting this hexadecimal value to 0x02 engages 'Fine-grained' dynamic power management for Turing/Ampere/Ada architectures. It instructs the PCI bus to physically sever the voltage rails to the NVIDIA dGPU when PRIME offloading is inactive, dropping the discrete card's power draw to near zero (D3cold state) while the Intel iGPU handles the desktop. Essential for battery life on the ASUS FX607V in Hybrid mode. Requires udev rules and nvidia-suspend.service to be properly configured.",
  },
  {
    id: "i915-fastboot",
    name: "i915.fastboot=1",
    category: "Graphics Subsystem",
    relevanceHybrid: 95,
    relevanceDgpu: 10,
    switches: "=1 (Enabled), =0 (Disabled, default)",
    recommendedValue: "i915.fastboot=1",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["i915", "intel", "fastboot", "plymouth", "flicker", "hybrid", "display"],
    verboseDescription: "A radical optimization for the Intel Graphics (i915) Direct Rendering Manager. Normally, the kernel will physically reset the display panel during the handover from the ASUS BIOS UEFI framebuffer. Injecting 'fastboot=1' instructs the kernel to trust the v340 BIOS's initial resolution matrix, fusing the bootloader screen directly into the Plymouth graphical boot and eliminating the destructive screen flicker between GRUB and the KDE SDDM login screen.",
  },
  {
    id: "acpi-enforce-resources",
    name: "acpi_enforce_resources=lax",
    category: "Diagnostics & Verbosity",
    relevanceHybrid: 70,
    relevanceDgpu: 70,
    switches: "=strict (Default), =lax, =no",
    recommendedValue: "acpi_enforce_resources=lax (when lm_sensors/asusctl need hardware access)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["acpi", "sensors", "lm_sensors", "asusctl", "embedded-controller", "thermal"],
    verboseDescription: "A highly volatile diagnostic parameter. By default, the kernel isolates certain ACPI memory regions to prevent userspace tools from colliding with firmware operations. Setting this to 'lax' tears down this barrier. While dangerous, it is often the only way to allow tools like 'lm_sensors' or 'asusctl' to penetrate the ASUS BIOS v340 matrix and extract raw thermal diode readouts and fan RPMs directly from the Embedded Controller.",
  },
  {
    id: "clocksource-tsc",
    name: "clocksource=tsc",
    category: "Processor & Scheduling",
    relevanceHybrid: 80,
    relevanceDgpu: 90,
    switches: "=tsc, =hpet, =acpi_pm, =kvm-clock",
    recommendedValue: "clocksource=tsc (combine with tsc=reliable)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["tsc", "clocksource", "timing", "latency", "cpu", "hpet"],
    verboseDescription: "Operating in tandem with 'tsc=reliable', this forces the kernel to utilize the Time Stamp Counter as the absolute master clock source for the entire operating system. Bypassing the High Precision Event Timer (HPET) completely removes the latency associated with querying an external motherboard chip, ensuring microsecond-perfect thread scheduling across the CPU and NVIDIA dGPU. Combine with tsc=reliable for maximum effect.",
  },
  {
    id: "rcu-nocbs",
    name: "rcu_nocbs=all",
    category: "Processor & Scheduling",
    relevanceHybrid: 60,
    relevanceDgpu: 85,
    switches: "=all, =[core list e.g., 0-15]",
    recommendedValue: "rcu_nocbs=all (latency-sensitive or dGPU workloads)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["rcu", "cpu", "latency", "scheduling", "interrupt", "kernel"],
    verboseDescription: "Read-Copy-Update (RCU) is a synchronization mechanism in the Linux kernel. Normally, RCU callbacks induce micro-interrupts on all CPU cores. By offloading these callbacks entirely ('nocbs=all'), you create a chemically isolated environment where background kernel housekeeping is shoved onto dedicated threads. This prevents latency spikes on cores actively engaged in feeding draw calls to the NVIDIA graphics pipeline.",
  },
  {
    id: "threadirqs",
    name: "threadirqs",
    category: "Processor & Scheduling",
    relevanceHybrid: 50,
    relevanceDgpu: 80,
    switches: "(Standalone flag)",
    recommendedValue: "threadirqs (audio/real-time sensitive environments)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["irq", "threads", "latency", "audio", "pipewire", "realtime"],
    verboseDescription: "A major structural alteration to the kernel's interrupt handling. This parameter forces all hardware interrupt handlers to operate as schedulable kernel threads. Instead of hardware interrupts violently preempting whatever the CPU is doing, they become managed processes. This drastically improves the real-time responsiveness of audio buffers (PipeWire) and USB peripherals (like mice) at the cost of slight overall CPU throughput overhead.",
  },
  {
    id: "preempt-full",
    name: "preempt=full",
    category: "Processor & Scheduling",
    relevanceHybrid: 50,
    relevanceDgpu: 95,
    switches: "=none, =voluntary (default Fedora), =full",
    recommendedValue: "preempt=full (dGPU gaming/low-latency)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["preempt", "latency", "scheduling", "gaming", "kwin", "realtime"],
    verboseDescription: "Synthesizes maximum kernel preemption. In Fedora Rawhide, the kernel is typically configured for voluntary preemption. Forcing it to 'full' allows high-priority tasks (like KDE KWin Wayland compositor threads or explicit game loops) to ruthlessly and instantly preempt lower-priority kernel processes. This is a critical catalyst for achieving absolute zero-latency frame pacing on the dGPU, especially during heavy background compilation.",
  },
  {
    id: "workqueue-power",
    name: "workqueue.power_efficient=Y",
    category: "Power & ACPI",
    relevanceHybrid: 95,
    relevanceDgpu: 20,
    switches: "=Y (Yes), =N (No, default)",
    recommendedValue: "workqueue.power_efficient=Y (Hybrid/battery mode)",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["workqueue", "power", "efficiency", "battery", "hybrid", "cpu"],
    verboseDescription: "A deep thermodynamic intervention for Hybrid mode. The kernel maintains unbound 'workqueues' for asynchronous tasks. By enabling 'power_efficient=Y', the kernel strictly binds these background tasks to CPU cores that are already awake and actively processing, rather than waking up sleeping cores. This significantly reduces thermal output and preserves battery life when operating in the Intel Hybrid matrix.",
  },
  {
    id: "random-trust-cpu",
    name: "random.trust_cpu=on",
    category: "System Core & Security",
    relevanceHybrid: 90,
    relevanceDgpu: 90,
    switches: "=on, =off (default)",
    recommendedValue: "random.trust_cpu=on",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["entropy", "random", "rdrand", "boot", "cryptography", "intel"],
    verboseDescription: "Cryptographic entropy generation can block the boot process until enough 'randomness' is gathered from hardware timing variations. Injecting 'trust_cpu=on' commands the kernel to unconditionally trust the Intel CPU's internal hardware random number generator (RDRAND instruction set). This creates an immediate, infinite pool of entropy, shaving measurable seconds off the Fedora 43 boot time. Intel's RDRAND is generally trusted on modern silicon.",
  },
  {
    id: "pcie-port-pm",
    name: "pcie_port_pm=off",
    category: "Peripheral & I/O",
    relevanceHybrid: 60,
    relevanceDgpu: 80,
    switches: "=off, =force",
    recommendedValue: "pcie_port_pm=off (if Wi-Fi or SD card causes dropouts)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["pcie", "power", "wifi", "bluetooth", "peripheral", "stability"],
    verboseDescription: "ASUS motherboards aggressively power-manage internal PCIe ports, specifically those routing to Wi-Fi/Bluetooth cards and SD card readers. This can induce connection dropouts. By forcefully disabling PCIe Port Power Management globally, you ensure constant voltage to all interconnected bus lanes. This trades thermal efficiency for absolute, ironclad peripheral stability.",
  },
  {
    id: "slab-nomerge",
    name: "slab_nomerge",
    category: "Memory & Hardware Isolation",
    relevanceHybrid: 50,
    relevanceDgpu: 50,
    switches: "(Standalone flag)",
    recommendedValue: "slab_nomerge (security-hardened development systems)",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["slab", "memory", "security", "heap", "kernel", "exploit-mitigation"],
    verboseDescription: "A highly advanced security and debugging mechanism for the kernel heap. Normally, the Linux SLUB allocator merges memory caches of the same size to save space. Injecting this parameter segregates all memory caches. While it slightly increases overhead on your 16GB DDR5 memory pool, it eliminates an entire class of buffer-overflow heap-exploitation attacks, vital for testing bleeding-edge Rawhide network protocols.",
  },
  {
    id: "page-poison",
    name: "page_poison=1",
    category: "Diagnostics & Verbosity",
    relevanceHybrid: 20,
    relevanceDgpu: 20,
    switches: "=1 (Enabled), =0 (Disabled, default)",
    recommendedValue: "page_poison=1 (driver debugging only — massive performance hit)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["memory", "debugging", "use-after-free", "kernel", "driver", "testing"],
    verboseDescription: "An extreme memory debugging tool. When a process frees memory, the data remains in the DDR5 lattice until overwritten. Injecting 'page_poison=1' forces the kernel to instantly overwrite all newly freed memory pages with a specific byte pattern (0xAA). This exposes use-after-free bugs in experimental Rawhide drivers by forcing immediate kernel panics when accessed. Never use in a normal system — causes severe performance degradation.",
  },
  {
    id: "slub-debug",
    name: "slub_debug=FZP",
    category: "Diagnostics & Verbosity",
    relevanceHybrid: 30,
    relevanceDgpu: 30,
    switches: "=FZP (Sanity+Redzone+Poison), =U (User tracking), =O (Object)",
    recommendedValue: "slub_debug=FZP (driver memory debugging only)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["slub", "memory", "debugging", "driver", "nvidia", "kernel", "profiling"],
    verboseDescription: "The ultimate diagnostic for memory allocation. By passing 'FZP' (Sanity Checks, Redzoning, and Poisoning), the kernel wraps every single internal memory allocation in a protective debugging matrix. It tracks exactly where every byte of your 16GB DDR5 is going. It causes massive performance degradation but is the only way to trace catastrophic memory leaks inside proprietary NVIDIA kernel modules or bleeding-edge Rawhide drivers.",
  },
  {
    id: "initcall-debug",
    name: "initcall_debug",
    category: "Diagnostics & Verbosity",
    relevanceHybrid: 60,
    relevanceDgpu: 60,
    switches: "(Standalone flag)",
    recommendedValue: "initcall_debug (only when debugging boot hangs)",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["initcall", "debug", "boot", "timing", "acpi", "driver", "hang"],
    verboseDescription: "A highly verbose profiling tool. When injected, the kernel logs the exact microsecond timestamp before and after the initialization of every single built-in module and ACPI sequence. If the ASUS BIOS v340 is causing a multi-second hang during the execution of a specific driver (like the sound card or WMI bridge), this parameter outputs the exact proof into the dmesg buffer for forensic analysis.",
  },
  {
    id: "loglevel-max",
    name: "loglevel=7",
    category: "Diagnostics & Verbosity",
    relevanceHybrid: 50,
    relevanceDgpu: 50,
    switches: "=[0-7] (0=Emergency, 3=Error, 5=Notice, 7=Debug)",
    recommendedValue: "loglevel=7 (debugging only, remove for daily use)",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["loglevel", "debug", "dmesg", "verbose", "boot", "kernel"],
    verboseDescription: "The floodgates of system logs. Setting the loglevel to the maximum value of 7 (Debug) commands the kernel to output every single piece of internal telemetry, warning, and debug data directly to the active TTY. Combined with the removal of 'quiet', this turns the ASUS F16's display into a rapidly scrolling cascade of raw, unfiltered system data during the boot sequence. Invaluable for diagnosing intermittent hardware issues on Rawhide.",
  },
  {
    id: "l1tf-off",
    name: "l1tf=off",
    category: "Processor & Security",
    relevanceHybrid: 75,
    relevanceDgpu: 85,
    switches: "=off, =full, =full,force",
    recommendedValue: "l1tf=off (isolated gaming/dev system, re-enable on shared systems)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["l1tf", "security", "spectre", "intel", "cpu", "mitigation", "ipc"],
    verboseDescription: "Specifically targets the L1 Terminal Fault (Foreshadow) vulnerability present in Intel silicon. By neutralizing this mitigation, you restore direct, un-flushed access to the L1 CPU cache during context switches. While it exposes the hyperthreading matrix to side-channel attacks, it restores a measurable percentage of raw IPC (Instructions Per Clock) throughput, beneficial for CPU-bound dGPU game emulation. Part of the broader 'mitigations=off' strategy applied selectively.",
  },
  {
    id: "mds-off",
    name: "mds=off",
    category: "Processor & Security",
    relevanceHybrid: 75,
    relevanceDgpu: 85,
    switches: "=off, =full, =full,nosmt",
    recommendedValue: "mds=off (isolated gaming/dev system only)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["mds", "zombieload", "security", "intel", "cpu", "mitigation", "syscall"],
    verboseDescription: "Neutralizes the Microarchitectural Data Sampling (Zombieload) mitigations. Similar to l1tf, this prevents the kernel from scrubbing internal CPU buffers (like store buffers and fill buffers) when transitioning between user-space and kernel-space. Disabling this defense acts as a catalyst for lowering system call latency on the Intel processor in isolated environments. Combine only with other mitigation-off flags as part of a deliberate performance tuning strategy.",
  },
  {
    id: "zram-devices",
    name: "zram.num_devices=1",
    category: "Memory & Hardware Isolation",
    relevanceHybrid: 80,
    relevanceDgpu: 80,
    switches: "=[integer] (number of zram devices)",
    recommendedValue: "zram.num_devices=1",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["zram", "memory", "swap", "compressed", "ddr5", "systemd"],
    verboseDescription: "A pre-requisite for advanced compressed memory architectures. While zswap acts as a cache for a physical NVMe swapfile, zram creates a block device existing purely within your 16GB DDR5 lattice. Setting the device count to 1 explicitly initializes the module to allow systemd-zram-setup to dynamically allocate a high-speed, lz4 or zstd-compressed swap drive directly in memory, reducing NVMe wear significantly.",
  },
  {
    id: "nouveau-modeset-0",
    name: "nouveau.modeset=0",
    category: "Graphics Subsystem",
    relevanceHybrid: 85,
    relevanceDgpu: 100,
    switches: "=0 (Disabled), =1 (Enabled)",
    recommendedValue: "nouveau.modeset=0",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["nouveau", "nvidia", "drm", "modeset", "blacklist", "proprietary"],
    verboseDescription: "A secondary, aggressive blockade against the open-source nouveau driver. While blacklisting prevents the module from loading initially, injecting 'modeset=0' mathematically destroys its ability to interface with the Direct Rendering Manager even if loaded later by a rogue system process. Use this alongside rd.driver.blacklist=nouveau for belt-and-suspenders protection when running the proprietary NVIDIA stack.",
  },
  {
    id: "intel-iommu-igfx",
    name: "intel_iommu=igfx_off",
    category: "Memory & Hardware Isolation",
    relevanceHybrid: 20,
    relevanceDgpu: 95,
    switches: "=on, =off, =igfx_off",
    recommendedValue: "intel_iommu=igfx_off (strict dGPU-only environments)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["iommu", "intel", "igpu", "dma", "dGPU", "performance", "memory"],
    verboseDescription: "A hyper-specialized parameter for strict dGPU environments. While 'intel_iommu=on' is needed for overall hardware isolation, passing 'igfx_off' explicitly severs the Intel integrated graphics from the IOMMU translation matrix. Since the iGPU is not being used to render frames in a pure dGPU state, excluding it prevents the IOMMU subsystem from wasting CPU cycles managing memory mappings for an idle graphics processor.",
  },
  {
    id: "kvm-ignore-msrs",
    name: "kvm.ignore_msrs=1",
    category: "System Core & Security",
    relevanceHybrid: 80,
    relevanceDgpu: 80,
    switches: "=1 (Enabled), =0 (Disabled, default)",
    recommendedValue: "kvm.ignore_msrs=1 (if running Windows VMs via KVM)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["kvm", "virtualization", "msr", "windows", "qemu", "vm"],
    verboseDescription: "Critical for running Windows virtual environments (like Windows VMs via QEMU/KVM) on Fedora Rawhide. Windows often attempts to read or write to undocumented Model-Specific Registers (MSRs) on the Intel CPU. By default, KVM rejects these, causing the VM to panic. Injecting this parameter forces KVM to silently ignore the requests, stabilizing the virtualized guest operating system.",
  },
  {
    id: "processor-ignore-ppc",
    name: "processor.ignore_ppc=1",
    category: "Power & ACPI",
    relevanceHybrid: 40,
    relevanceDgpu: 95,
    switches: "=1 (Enabled), =0 (Disabled, default)",
    recommendedValue: "processor.ignore_ppc=1 (performance mode, AC power only)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["acpi", "ppc", "thermal", "cpu", "performance", "asus", "bios"],
    verboseDescription: "A highly volatile thermal override. The ASUS BIOS v340 ACPI tables dictate strict Performance Present Capabilities (PPC) to limit the Intel CPU's maximum frequency when thermal limits are approaching. Injecting this parameter commands the Linux kernel to violently ignore the BIOS's thermal throttling requests. This unlocks maximum frequency scaling, transferring all thermal responsibility to the hardware's own trip points. Use on AC power only.",
  },
  {
    id: "idle-nomwait",
    name: "idle=nomwait",
    category: "Processor & Scheduling",
    relevanceHybrid: 50,
    relevanceDgpu: 85,
    switches: "=poll (Maximum power, no sleep), =halt, =nomwait",
    recommendedValue: "idle=nomwait (if mwait causes micro-stutters)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["cpu", "idle", "mwait", "latency", "cstate", "scheduling"],
    verboseDescription: "Alters the fundamental mechanism the CPU uses to enter idle states. By default, Intel processors use the 'mwait' instruction, which is highly efficient but can have specific latency wake-up penalties. Forcing 'nomwait' makes the kernel synthesize older, slightly less power-efficient idle instructions (like 'halt'). This serves as an obscure stabilizer if 'mwait' causes micro-stutters when waking the CPU to feed the NVIDIA data bus.",
  },
  {
    id: "intel-idle-cstate",
    name: "intel_idle.max_cstate=1",
    category: "Power & PCIe Bus",
    relevanceHybrid: 10,
    relevanceDgpu: 100,
    switches: "=[0-9] (0=Disable intel_idle, 1=C1 only, higher=deeper sleep)",
    recommendedValue: "intel_idle.max_cstate=1 (maximum dGPU performance, AC power only)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["cpu", "cstate", "intel_idle", "power", "latency", "gaming"],
    verboseDescription: "The ultimate decimation of CPU power saving via the intel_idle driver. Setting it to 1 restricts the CPU from entering anything deeper than the C1 sleep state. The CPU cores never fully shut down; they remain instantly ready to synthesize data. This is the most battery-destroying catalyst for absolutely flawless frame generation on the ASUS F16. Use only on AC power and combine with nvidia.NVreg_DynamicPowerManagement=0x00 in dGPU mode.",
  },
  {
    id: "button-lid-init",
    name: "button.lid_init_state=open",
    category: "ASUS Firmware & ACPI",
    relevanceHybrid: 75,
    relevanceDgpu: 75,
    switches: "=open, =closed, =ignore",
    recommendedValue: "button.lid_init_state=open",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["asus", "acpi", "lid", "sleep", "logind", "firmware", "embedded-controller"],
    verboseDescription: "A synthetic bridge over a common ASUS embedded controller flaw. Occasionally, upon booting, the firmware misreports the laptop lid as 'closed', causing the systemd logind service to instantly issue a sleep command, creating an infinite sleep-wake loop. Forcing 'open' permanently overrides the initial ACPI polling, ensuring the kernel assumes the display matrix is active and exposed until the first physical hardware interrupt is triggered by the hinge.",
  },
  {
    id: "i8042-dumbkbd",
    name: "i8042.dumbkbd=1",
    category: "Peripheral & I/O",
    relevanceHybrid: 65,
    relevanceDgpu: 65,
    switches: "=1 (Enabled), =0 (Disabled, default)",
    recommendedValue: "i8042.dumbkbd=1 (if keyboard repeats or fails to register at boot)",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["keyboard", "i8042", "ps2", "boot", "asus", "input"],
    verboseDescription: "An archaic but sometimes necessary parameter for the TUF series keyboards. If the advanced ASUS keyboard backlighting or N-key rollover matrix conflicts with the standard Linux PS/2 driver initialization, keys may repeat infinitely or fail to register. Injecting 'dumbkbd' strips away all advanced hardware interrogation during boot, forcing the kernel to treat the F16 keyboard as a generic input device until the userspace USB daemon takes control.",
  },
  {
    id: "nvidia-powermizer",
    name: "nvidia.NVreg_RegistryDwords=\"PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerDefault=0x1; PowerMizerDefaultAC=0x1\"",
    category: "Graphics Subsystem",
    relevanceHybrid: 10,
    relevanceDgpu: 100,
    switches: "(Hexadecimal Registry Strings — semicolon-separated key=value pairs)",
    recommendedValue: "Only in dGPU mode on AC power for maximum performance",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["nvidia", "powermizer", "performance", "pstate", "dgpu", "registry"],
    verboseDescription: "A highly volatile registry override for the proprietary NVIDIA matrix. This hexadecimal string locks the Turing/Ampere/Ada core into its maximum performance P-state (P0). It ignores all thermal and power-saving directives from the ASUS embedded controller, forcing the dGPU to consume maximum voltage and maintain peak clock speeds perpetually for absolute zero-latency frame synthesis. Only use on AC power. Monitor temperatures closely.",
  },
  {
    id: "swiotlb",
    name: "swiotlb=65536",
    category: "Memory & Hardware Isolation",
    relevanceHybrid: 80,
    relevanceDgpu: 95,
    switches: "=[integer] (Number of 2KB I/O slabs; default=2048)",
    recommendedValue: "swiotlb=65536 (if DMA errors appear in dmesg)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["swiotlb", "dma", "memory", "nvidia", "iommu", "ddr5", "nvme"],
    verboseDescription: "Software Input Output Translation Lookaside Buffer. With a 16GB DDR5 lattice and a high-bandwidth NVIDIA dGPU, device drivers performing direct memory access (DMA) can fail when addressing memory above the 4GB boundary. Injecting 65536 massively expands the SWIOTLB bounce buffer matrix. This synthesizes an unbreakable bridge for immense data payloads traveling between the NVMe swap partition and the discrete graphics processor.",
  },
  {
    id: "rd-luks-discard",
    name: "rd.luks.options=discard",
    category: "Storage Subsystem",
    relevanceHybrid: 90,
    relevanceDgpu: 90,
    switches: "=discard, =timeout, =sector-size",
    recommendedValue: "rd.luks.options=discard (if root/swap is on LUKS, and security tradeoff is acceptable)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["luks", "encryption", "discard", "trim", "nvme", "dracut", "storage"],
    verboseDescription: "When your NVMe swap or BTRFS root is encapsulated within a LUKS cryptographic container, standard SSD TRIM commands are blocked for security. Passing 'discard' to the early dracut initramfs forcefully enables TRIM through the encryption layer, allowing the NAND controller to reclaim unused blocks and vastly accelerating I/O throughput at a minor cost to cryptographic deniability (TRIM reveals which blocks are unused to an attacker with physical access).",
  },
  {
    id: "pcie-aspm-policy",
    name: "pcie_aspm.policy=performance",
    category: "Power & PCIe Bus",
    relevanceHybrid: 40,
    relevanceDgpu: 90,
    switches: "=default, =performance, =powersave, =powersupersave",
    recommendedValue: "pcie_aspm.policy=performance (dGPU) or pcie_aspm.policy=powersupersave (Hybrid)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["pcie", "aspm", "performance", "power", "nvidia", "nvme", "bandwidth"],
    verboseDescription: "While 'pcie_aspm=off' entirely severs Active State Power Management, this parameter is a more calculated agent. It instructs the PCI subsystem to prioritize maximum throughput over power savings across the entire motherboard bus. It forces the PCIe lanes connecting your NVIDIA dGPU and Gen4 NVMe drive into maximum bandwidth configurations without completely neutralizing the underlying firmware specifications.",
  },
  {
    id: "snd-hda-intel-power",
    name: "snd_hda_intel.power_save=0 snd_hda_intel.power_save_controller=N",
    category: "Peripheral & I/O",
    relevanceHybrid: 70,
    relevanceDgpu: 85,
    switches: "power_save=0 (Disabled), =1 (1 second timeout); power_save_controller=N/Y",
    recommendedValue: "snd_hda_intel.power_save=0 snd_hda_intel.power_save_controller=N (if audio pops occur)",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["audio", "hda", "intel", "power", "pipewire", "pop", "latency"],
    verboseDescription: "Eliminates the power-saving protocols for the Intel High Definition Audio controller. When the ASUS FX607V audio codec enters a low-power state, waking it can induce an audible 'pop' in headphones and a latency spike in PipeWire audio servers. Forcing these to 0/N perpetually energizes the audio hardware, guaranteeing instantaneous acoustic synthesis during heavy graphical loads. A common fix for the familiar 'audio pop on first sound' symptom on ASUS laptops.",
  },
  {
    id: "panic-reboot",
    name: "panic=10 oops=panic",
    category: "Diagnostics & Verbosity",
    relevanceHybrid: 80,
    relevanceDgpu: 80,
    switches: "panic=[seconds] (0=hang indefinitely); oops=panic or oops=continue",
    recommendedValue: "panic=10 oops=panic (Rawhide development environment)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["panic", "oops", "reboot", "kernel", "rawhide", "debugging", "stability"],
    verboseDescription: "The ultimate fail-safe for bleeding-edge Fedora Rawhide development. A kernel 'oops' is a non-fatal anomaly, but injecting 'oops=panic' forces the kernel to interpret any deviation as a catastrophic failure, triggering an immediate lockdown. The 'panic=10' parameter acts as an automated fail-safe, rebooting the ASUS motherboard exactly 10 seconds after the crash, ensuring your system doesn't deadlock in an unrecoverable state.",
  },
  {
    id: "intel-pstate-no-hwp",
    name: "intel_pstate=no_hwp",
    category: "Processor & Scheduling",
    relevanceHybrid: 50,
    relevanceDgpu: 85,
    switches: "=no_hwp (Disable HWP), =active (Default with HWP), =passive",
    recommendedValue: "intel_pstate=no_hwp (if HWP causes scheduling interference)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["intel", "pstate", "hwp", "cpu", "scheduling", "frequency", "governor"],
    verboseDescription: "Intel Hardware P-States (HWP) allow the CPU to internally and autonomously manage its own clock speeds, ignoring the OS scheduler. In a highly volatile dGPU override state, you may want the Linux kernel's CPU scheduler to maintain absolute dominance. Injecting 'no_hwp' severs the autonomous silicon logic, dragging frequency scaling control back to the Fedora 43 kernel matrix for precise workload tuning.",
  },
  {
    id: "earlyprintk-efi",
    name: "earlyprintk=efi,keep",
    category: "Diagnostics & Verbosity",
    relevanceHybrid: 75,
    relevanceDgpu: 75,
    switches: "=vga, =efi, =serial,[baud], =keep (retain after init)",
    recommendedValue: "earlyprintk=efi,keep (only when debugging pre-DRM boot hangs)",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["earlyprintk", "uefi", "debug", "boot", "panic", "display", "framebuffer"],
    verboseDescription: "An extreme diagnostic parameter. If the Rawhide kernel locks up before the Direct Rendering Manager (DRM) or standard TTY consoles initialize, the screen remains black. This parameter bypasses the standard display topology and writes raw initialization strings directly into the UEFI framebuffer allocated by the ASUS v340 BIOS, preserving panic text visually on the panel for forensic analysis.",
  },
  {
    id: "nvme-noacpi",
    name: "nvme.noacpi=1",
    category: "Storage Subsystem",
    relevanceHybrid: 50,
    relevanceDgpu: 80,
    switches: "=1 (Enabled), =0 (Disabled, default)",
    recommendedValue: "nvme.noacpi=1 (if BIOS causes NVMe lockups)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["nvme", "acpi", "storage", "asus", "bios", "lockup", "firmware"],
    verboseDescription: "Violently severs the communication bridge between the PCIe NVMe controller and the ASUS Advanced Configuration and Power Interface (ACPI) tables. If the v340 BIOS contains faulty thermal or power reporting for the SSD, it can induce a storage lockup. This parameter forces the Linux kernel to query the NVMe NAND flash directly, bypassing the manufacturer's firmware matrix entirely.",
  },
  {
    id: "pci-noaer",
    name: "pci=noaer",
    category: "Peripheral & I/O",
    relevanceHybrid: 30,
    relevanceDgpu: 85,
    switches: "(Standalone flag — part of pci= option list)",
    recommendedValue: "pci=noaer (if AER errors flood dmesg during GPU workloads)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["pci", "pcie", "aer", "error", "nvidia", "dmesg", "gpu", "interrupt"],
    verboseDescription: "Disables Advanced Error Reporting (AER) on the PCI Express bus. During massive data transfers between the 16GB DDR5 memory pool and the NVIDIA dGPU, non-fatal PCIe bus errors can flood the dmesg log, consuming CPU cycles simply to report microscopic voltage fluctuations. Disabling AER mathematically silences this telemetry, sacrificing hardware diagnostics for raw throughput and reduced interrupt latency.",
  },
  {
    id: "ipv6-disable",
    name: "ipv6.disable=1",
    category: "System Core & Security",
    relevanceHybrid: 70,
    relevanceDgpu: 70,
    switches: "=1 (Disabled), =0 (Enabled, default)",
    recommendedValue: "ipv6.disable=1 (only if strictly IPv4-only environment)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["ipv6", "network", "tcp", "kernel", "performance", "ram"],
    verboseDescription: "Completely removes the entire IPv6 networking stack from kernel space. If your development environment relies strictly on IPv4 topologies and you have no IPv6 infrastructure, the IPv6 stack consumes RAM and CPU cycles in the background. Injecting this parameter prevents the network module from even binding the IPv6 subsystem. Not recommended for most modern networks which increasingly rely on IPv6.",
  },
  {
    id: "vsyscall-none",
    name: "vsyscall=none",
    category: "Processor & Security",
    relevanceHybrid: 85,
    relevanceDgpu: 85,
    switches: "=none, =emulate (default), =native",
    recommendedValue: "vsyscall=none",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["vsyscall", "security", "rop", "aslr", "vdso", "exploit-mitigation"],
    verboseDescription: "A targeted security hardening against legacy x86 architecture. Virtual System Calls (vsyscall) map a static memory page to accelerate time-of-day queries, but this statically predictable memory location is a known vector for Return-Oriented Programming (ROP) exploits. By setting to 'none', you force the system to utilize modernized, dynamically randomized vDSO pages, significantly hardening the Rawhide OS against memory-based attacks.",
  },
  {
    id: "cgroup-disable-memory",
    name: "cgroup_disable=memory",
    category: "Memory & Hardware Isolation",
    relevanceHybrid: 40,
    relevanceDgpu: 80,
    switches: "=memory, =memory,cpu,io (comma-separated subsystems)",
    recommendedValue: "cgroup_disable=memory (single-user performance systems only)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["cgroup", "memory", "systemd", "performance", "overhead", "cpu"],
    verboseDescription: "Disables the memory controller within the Linux Control Groups (cgroups) centrifuge. While cgroups are required for systemd, disabling the *memory* specific tracking slightly reduces the overhead of page-fault accounting. For a monolithic gaming or compilation state on the ASUS F16, this frees up a microscopic but measurable amount of CPU bandwidth across all 16GB of DDR5. Note: breaks memory accounting for all containers and VMs.",
  },
  {
    id: "nohz-full",
    name: "nohz_full=1-15",
    category: "Processor & Scheduling",
    relevanceHybrid: 20,
    relevanceDgpu: 95,
    switches: "=[core list] (e.g., 1-15 to exclude core 0)",
    recommendedValue: "nohz_full=1-15 (combine with isolcpus for real-time workloads)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["nohz", "cpu", "tickless", "latency", "realtime", "scheduling", "interrupt"],
    verboseDescription: "Synthesizes a completely tickless kernel for specified CPU cores. Standard Linux scheduling sends hundreds of timer interrupts (ticks) per second to every core. By designating cores 1 through 15 as 'nohz_full', you mathematically isolate them. When running a massive dGPU-bound application, the kernel entirely stops interrupting those cores, allowing 100% pure, unadulterated focus on the workload. Requires matching isolcpus for full effect.",
  },
  {
    id: "isolcpus",
    name: "isolcpus=1-15",
    category: "Processor & Scheduling",
    relevanceHybrid: 10,
    relevanceDgpu: 95,
    switches: "=[core list] (e.g., 1-15), isolcpus=managed_irq,domain,[core list]",
    recommendedValue: "isolcpus=1-15 (combine with nohz_full, use taskset to pin workloads)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["isolcpus", "cpu", "isolation", "latency", "realtime", "taskset", "scheduling"],
    verboseDescription: "The most aggressive form of CPU core isolation. When combined with 'nohz_full', this parameter rips CPU cores entirely out of the standard Linux scheduler. The OS will refuse to place any background processes on these cores. You must manually bind your target applications to these cores using 'taskset', creating an absolutely pristine, zero-latency execution environment for extreme dGPU synchronization.",
  },
  {
    id: "usb-buffer",
    name: "usbcore.usbfs_memory_mb=1000",
    category: "Peripheral & I/O",
    relevanceHybrid: 80,
    relevanceDgpu: 80,
    switches: "=[integer] (Megabytes, default=16)",
    recommendedValue: "usbcore.usbfs_memory_mb=1000 (if using high-bandwidth USB capture devices)",
    positionalParams: null,
    riskLevel: "moderate",
    tags: ["usb", "memory", "buffer", "peripheral", "capture", "bandwidth", "ddr5"],
    verboseDescription: "Massively expands the chemical buffer limit for USB device memory. By default, the Linux kernel restricts the amount of DDR5 memory a USB device can request. If you are plugging high-bandwidth peripherals or uncompressed capture cards into the ASUS F16's USB-C ports, the default 16MB limit will bottleneck the stream. This parameter expands the memory pool to 1000MB, ensuring flawless, uninterrupted I/O throughput.",
  },
  {
    id: "random-trust-bootloader",
    name: "random.trust_bootloader=on",
    category: "System Core & Security",
    relevanceHybrid: 90,
    relevanceDgpu: 90,
    switches: "=on, =off (default)",
    recommendedValue: "random.trust_bootloader=on",
    positionalParams: null,
    riskLevel: "safe",
    tags: ["entropy", "random", "grub", "uefi", "boot", "cryptography"],
    verboseDescription: "Forces the Rawhide kernel to immediately trust the cryptographic entropy seeds passed down from the GRUB bootloader and the ASUS v340 UEFI matrix. It jumpstarts the kernel's internal random number generator pool, preventing the systemd initialization phase from hanging while waiting for atmospheric noise or disk I/O entropy to reach the necessary threshold. Works alongside random.trust_cpu=on for fastest boot time.",
  },
  {
    id: "apparmor-disable",
    name: "apparmor=0 lsm=bpf,yama",
    category: "System Core & Security",
    relevanceHybrid: 60,
    relevanceDgpu: 60,
    switches: "apparmor=0/1; lsm=[comma-separated list of LSM names]",
    recommendedValue: "Only if AppArmor profiles are blocking proprietary driver daemons",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["apparmor", "lsm", "security", "mac", "nvidia", "selinux", "bpf"],
    verboseDescription: "Strips away the AppArmor Mandatory Access Control (MAC) matrix. Fedora typically utilizes SELinux, but if AppArmor profiles leak into the Rawhide chemical mix via third-party packages, they can catastrophically block proprietary NVIDIA daemon execution. This injection zeros out AppArmor and forcefully redefines the Linux Security Module (LSM) topology to only include basic process tracing (yama) and eBPF capabilities.",
  },
  {
    id: "i915-force-probe",
    name: "i915.force_probe=*",
    category: "Graphics Subsystem",
    relevanceHybrid: 100,
    relevanceDgpu: 10,
    switches: "=[PCI Device ID] (e.g., 46a6), =* (force all)",
    recommendedValue: "i915.force_probe=[your iGPU PCI ID] (prefer specific ID over wildcard)",
    positionalParams: null,
    riskLevel: "advanced",
    tags: ["i915", "intel", "igpu", "probe", "rawhide", "drm", "experimental"],
    verboseDescription: "A highly experimental bridge for the Intel iGPU. If you are running an incredibly new, bleeding-edge Rawhide kernel that does not officially recognize the exact stepping of the Intel silicon inside your ASUS FX607V, the i915 driver will refuse to bind. Passing the wildcard asterisk forces the driver to ignore its internal safeguard matrix and violently attempt initialization regardless of the hardware ID. Prefer a specific PCI device ID (from lspci) over the wildcard in production.",
  },
];

router.get("/parameters", (req: Request, res: Response) => {
  const { category, graphicsMode, search, riskLevel } = req.query as Record<string, string>;
  let results = [...PARAMETERS];

  if (category) {
    results = results.filter((p) => p.category === category);
  }
  if (riskLevel) {
    results = results.filter((p) => p.riskLevel === riskLevel);
  }
  if (search) {
    const q = search.toLowerCase();
    results = results.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        p.verboseDescription.toLowerCase().includes(q) ||
        p.tags.some((t) => t.includes(q)) ||
        p.category.toLowerCase().includes(q),
    );
  }

  // Sort by relevance for the chosen graphics mode
  if (graphicsMode === "dgpu") {
    results.sort((a, b) => b.relevanceDgpu - a.relevanceDgpu);
  } else {
    results.sort((a, b) => b.relevanceHybrid - a.relevanceHybrid);
  }

  res.json(results);
});

router.get("/parameters/:id", (req: Request, res: Response) => {
  const param = PARAMETERS.find((p) => p.id === req.params["id"]);
  if (!param) {
    res.status(404).json({ error: "Parameter not found" });
    return;
  }
  res.json(param);
});

router.get("/categories", (_req: Request, res: Response) => {
  const categoryMeta: Record<string, string> = {
    "Graphics Subsystem": "NVIDIA, Intel iGPU, DRM, Wayland, display output",
    "Memory & Hardware Isolation": "IOMMU, VRAM, DDR5 tuning, THP, zswap, zram",
    "ASUS Firmware & ACPI": "BIOS v340 quirks, hotkeys, backlight, ACPI tables",
    "CPU & Power Management": "Intel P-state, sleep states, TSC, watchdog",
    "Storage & Filesystem": "BTRFS, LUKS, NVMe, dracut, compression",
    "Diagnostics & Verbosity": "Kernel log verbosity, systemd debug, RHGB, initcall",
    "Security & Integrity": "SELinux, kernel lockdown, mitigations, audit",
    "Display & Output": "Resolution, refresh rate, framebuffer, connectors",
    "Processor & Security": "Intel security mitigations, IBT, L1TF, MDS, vsyscall",
    "Processor & Scheduling": "CPU scheduling, preemption, IRQ threading, TSC, RCU",
    "Power & PCIe Bus": "PCIe ASPM, C-states, NVMe power, intel_idle",
    "Power & ACPI": "S3 sleep, workqueue efficiency, BIOS thermal limits",
    "Storage Subsystem": "NVMe APST, LUKS discard, ACPI storage quirks",
    "Peripheral & I/O": "USB, PCIe port PM, audio, i8042 keyboard",
    "System Core & Security": "Module signing, audit, KVM, entropy, AppArmor, IPv6",
  };

  const counts: Record<string, number> = {};
  PARAMETERS.forEach((p) => {
    counts[p.category] = (counts[p.category] || 0) + 1;
  });

  const categories = Object.entries(counts).map(([name, count]) => ({
    name,
    count,
    description: categoryMeta[name] || "",
  }));

  res.json(categories);
});

router.get("/stats", (_req: Request, res: Response) => {
  const categoryCounts: Record<string, number> = {};
  const riskCounts = { safe: 0, moderate: 0, advanced: 0 };

  PARAMETERS.forEach((p) => {
    categoryCounts[p.category] = (categoryCounts[p.category] || 0) + 1;
    riskCounts[p.riskLevel as keyof typeof riskCounts]++;
  });

  const topHybrid = [...PARAMETERS]
    .sort((a, b) => b.relevanceHybrid - a.relevanceHybrid)
    .slice(0, 5)
    .map(({ id, name, relevanceHybrid }) => ({ id, name, relevanceHybrid }));

  const topDgpu = [...PARAMETERS]
    .sort((a, b) => b.relevanceDgpu - a.relevanceDgpu)
    .slice(0, 5)
    .map(({ id, name, relevanceDgpu }) => ({ id, name, relevanceDgpu }));

  res.json({
    totalParameters: PARAMETERS.length,
    categoryCounts: Object.entries(categoryCounts).map(([category, count]) => ({
      category,
      count,
    })),
    riskCounts,
    topHybridParams: topHybrid,
    topDgpuParams: topDgpu,
  });
});

export default router;
